server:
  port: 8080

spring:
    datasource:
      url: jdbc:oracle:thin:@//localhost:1521/XE
      username: system
      password: password
      driver-class-name: oracle.jdbc.OracleDriver

    jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
          properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle12cDialect



logging:
  level:
    org.springframework.security: TRACE
